name: Linter

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_call:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_GO: false
          VALIDATE_HTML: false
          VALIDATE_KUBERNETES_KUBECONFORM: false
          VALIDATE_JSCPD: false
          # GitHub actions often contain $(go list ./...) as part of commands
          GITHUB_ACTIONS_COMMAND_ARGS: -ignore SC2046
          IGNORE_GENERATED_FILES: true
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
